### ISSUE TITLE
Market redesign

### ISSUE THREAD

**Issue by c0gnize** [bitzlato/baseapp#64]
- [x] Use montserrat font (#65)
- [x] Change colors @c0gnize - (#75 deadline 23.08)
- [x] Landing page @trzmaxim - (#70, #89 deadline 24.08)
- [x] Change header @trzmaxim - (#94 deadline 25.08)
- [x] Add footer @trzmaxim - (#95 deadline 25.08)
- [x] Change popup control of  main menu and markets - (#94, #111)

**Comment by c0gnize** [comment]
Закрываю. Остальное отдельными issue
